// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: metrics.proto

package metrics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetricsIngestService_StreamMetrics_FullMethodName = "/metrics.MetricsIngestService/StreamMetrics"
)

// MetricsIngestServiceClient is the client API for MetricsIngestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsIngestServiceClient interface {
	StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Metric, StreamMetricsResponse], error)
}

type metricsIngestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsIngestServiceClient(cc grpc.ClientConnInterface) MetricsIngestServiceClient {
	return &metricsIngestServiceClient{cc}
}

func (c *metricsIngestServiceClient) StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Metric, StreamMetricsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetricsIngestService_ServiceDesc.Streams[0], MetricsIngestService_StreamMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Metric, StreamMetricsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsIngestService_StreamMetricsClient = grpc.ClientStreamingClient[Metric, StreamMetricsResponse]

// MetricsIngestServiceServer is the server API for MetricsIngestService service.
// All implementations must embed UnimplementedMetricsIngestServiceServer
// for forward compatibility.
type MetricsIngestServiceServer interface {
	StreamMetrics(grpc.ClientStreamingServer[Metric, StreamMetricsResponse]) error
	mustEmbedUnimplementedMetricsIngestServiceServer()
}

// UnimplementedMetricsIngestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricsIngestServiceServer struct{}

func (UnimplementedMetricsIngestServiceServer) StreamMetrics(grpc.ClientStreamingServer[Metric, StreamMetricsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedMetricsIngestServiceServer) mustEmbedUnimplementedMetricsIngestServiceServer() {}
func (UnimplementedMetricsIngestServiceServer) testEmbeddedByValue()                              {}

// UnsafeMetricsIngestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsIngestServiceServer will
// result in compilation errors.
type UnsafeMetricsIngestServiceServer interface {
	mustEmbedUnimplementedMetricsIngestServiceServer()
}

func RegisterMetricsIngestServiceServer(s grpc.ServiceRegistrar, srv MetricsIngestServiceServer) {
	// If the following call panics, it indicates UnimplementedMetricsIngestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricsIngestService_ServiceDesc, srv)
}

func _MetricsIngestService_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MetricsIngestServiceServer).StreamMetrics(&grpc.GenericServerStream[Metric, StreamMetricsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsIngestService_StreamMetricsServer = grpc.ClientStreamingServer[Metric, StreamMetricsResponse]

// MetricsIngestService_ServiceDesc is the grpc.ServiceDesc for MetricsIngestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricsIngestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metrics.MetricsIngestService",
	HandlerType: (*MetricsIngestServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMetrics",
			Handler:       _MetricsIngestService_StreamMetrics_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "metrics.proto",
}
