// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: metrics.proto

package metrics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricName int32

const (
	MetricName_METRIC_NAME_UNSPECIFIED MetricName = 0
	MetricName_CPU_USAGE               MetricName = 1
	MetricName_RAM_USAGE               MetricName = 2
	MetricName_DISK_USAGE              MetricName = 3
	MetricName_DISK_READ               MetricName = 4
	MetricName_DISK_WRITE              MetricName = 5
	MetricName_NET_RX                  MetricName = 6
	MetricName_NET_TX                  MetricName = 7
)

// Enum value maps for MetricName.
var (
	MetricName_name = map[int32]string{
		0: "METRIC_NAME_UNSPECIFIED",
		1: "CPU_USAGE",
		2: "RAM_USAGE",
		3: "DISK_USAGE",
		4: "DISK_READ",
		5: "DISK_WRITE",
		6: "NET_RX",
		7: "NET_TX",
	}
	MetricName_value = map[string]int32{
		"METRIC_NAME_UNSPECIFIED": 0,
		"CPU_USAGE":               1,
		"RAM_USAGE":               2,
		"DISK_USAGE":              3,
		"DISK_READ":               4,
		"DISK_WRITE":              5,
		"NET_RX":                  6,
		"NET_TX":                  7,
	}
)

func (x MetricName) Enum() *MetricName {
	p := new(MetricName)
	*p = x
	return p
}

func (x MetricName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricName) Descriptor() protoreflect.EnumDescriptor {
	return file_metrics_proto_enumTypes[0].Descriptor()
}

func (MetricName) Type() protoreflect.EnumType {
	return &file_metrics_proto_enumTypes[0]
}

func (x MetricName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricName.Descriptor instead.
func (MetricName) EnumDescriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	Name          MetricName             `protobuf:"varint,2,opt,name=name,proto3,enum=metrics.MetricName" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Metric) GetName() MetricName {
	if x != nil {
		return x.Name
	}
	return MetricName_METRIC_NAME_UNSPECIFIED
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StreamMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ReceivedCount uint64                 `protobuf:"varint,2,opt,name=receivedCount,proto3" json:"receivedCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMetricsResponse) Reset() {
	*x = StreamMetricsResponse{}
	mi := &file_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMetricsResponse) ProtoMessage() {}

func (x *StreamMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMetricsResponse.ProtoReflect.Descriptor instead.
func (*StreamMetricsResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *StreamMetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StreamMetricsResponse) GetReceivedCount() uint64 {
	if x != nil {
		return x.ReceivedCount
	}
	return 0
}

var File_metrics_proto protoreflect.FileDescriptor

const file_metrics_proto_rawDesc = "" +
	"\n" +
	"\rmetrics.proto\x12\ametrics\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x01\n" +
	"\x06Metric\x12\x18\n" +
	"\aagentId\x18\x01 \x01(\tR\aagentId\x12'\n" +
	"\x04name\x18\x02 \x01(\x0e2\x13.metrics.MetricNameR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"W\n" +
	"\x15StreamMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12$\n" +
	"\rreceivedCount\x18\x02 \x01(\x04R\rreceivedCount*\x8e\x01\n" +
	"\n" +
	"MetricName\x12\x1b\n" +
	"\x17METRIC_NAME_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tCPU_USAGE\x10\x01\x12\r\n" +
	"\tRAM_USAGE\x10\x02\x12\x0e\n" +
	"\n" +
	"DISK_USAGE\x10\x03\x12\r\n" +
	"\tDISK_READ\x10\x04\x12\x0e\n" +
	"\n" +
	"DISK_WRITE\x10\x05\x12\n" +
	"\n" +
	"\x06NET_RX\x10\x06\x12\n" +
	"\n" +
	"\x06NET_TX\x10\a2Z\n" +
	"\x14MetricsIngestService\x12B\n" +
	"\rStreamMetrics\x12\x0f.metrics.Metric\x1a\x1e.metrics.StreamMetricsResponse(\x01B\x11Z\x0f./proto;metricsb\x06proto3"

var (
	file_metrics_proto_rawDescOnce sync.Once
	file_metrics_proto_rawDescData []byte
)

func file_metrics_proto_rawDescGZIP() []byte {
	file_metrics_proto_rawDescOnce.Do(func() {
		file_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)))
	})
	return file_metrics_proto_rawDescData
}

var file_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_metrics_proto_goTypes = []any{
	(MetricName)(0),               // 0: metrics.MetricName
	(*Metric)(nil),                // 1: metrics.Metric
	(*StreamMetricsResponse)(nil), // 2: metrics.StreamMetricsResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_metrics_proto_depIdxs = []int32{
	0, // 0: metrics.Metric.name:type_name -> metrics.MetricName
	3, // 1: metrics.Metric.timestamp:type_name -> google.protobuf.Timestamp
	1, // 2: metrics.MetricsIngestService.StreamMetrics:input_type -> metrics.Metric
	2, // 3: metrics.MetricsIngestService.StreamMetrics:output_type -> metrics.StreamMetricsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_metrics_proto_init() }
func file_metrics_proto_init() {
	if File_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metrics_proto_goTypes,
		DependencyIndexes: file_metrics_proto_depIdxs,
		EnumInfos:         file_metrics_proto_enumTypes,
		MessageInfos:      file_metrics_proto_msgTypes,
	}.Build()
	File_metrics_proto = out.File
	file_metrics_proto_goTypes = nil
	file_metrics_proto_depIdxs = nil
}
